# let's ignore symlinks, otherwise certain hooks complain on Windows
exclude: '^(\.activate\.sh|docs/changelog\.rst)$'
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-added-large-files
        language_version: python3.6
    -   id: check-byte-order-marker
        language_version: python3.6
    -   id: check-json
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: fix-encoding-pragma
        language_version: python3.6
        args:
        - --remove
    -   id: name-tests-test
        language_version: python3.6
    -   id: trailing-whitespace
        language_version: python3.6
        # this hook doesn't seem to honor the global exclude setting
        exclude: '^(\.activate\.sh|docs/changelog\.rst)$'
    -   id: requirements-txt-fixer
        language_version: python3.6
        files: requirements-dev.txt
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.6
    hooks:
    -   id: flake8
        exclude: ^docs
        language_version: python3.6
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        language_version: python3.6
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
        args: [
            '--remove-import', 'from __future__ import absolute_import',
            '--remove-import', 'from __future__ import print_function',
            '--remove-import', 'from __future__ import unicode_literals',
        ]
